services:
  node-app:
    build:
      context: .
      dockerfile: node.Dockerfile # Node image
    ports:
      - "3000:3000"


  nginx:
    image: nginx:latest
    container_name: nginx-server
    ports:
      - "80:80"
    volumes:
      # Wir reichen nur die Konfigurationsdateien von au√üen hinein
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./etc/nginx/conf.d/proxy.conf:/etc/nginx/conf.d/proxy.conf:ro
      - ./etc/nginx/sites-available/finance-hub.local:/etc/nginx/sites-available/finance-hub.local:ro
      # Trick: Wir mounten den Ordner auf sites-enabled, damit Nginx die Config findet
      - ./etc/nginx/sites-available:/etc/nginx/sites-enabled:ro
      - ./frontend/html:/usr/share/nginx/html:ro
    depends_on:
      - node-app